### ISSUE TITLE
Travis failure when updating to Pytest 3.7.*

### ISSUE THREAD

**Issue by marco-c** [mozilla/coverage-crawler#140]
E.g. https://github.com/mozilla/coverage-crawler/pull/139

The error is:
```
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest.py", line 10, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/fixtures.py", line 17, in <module>
    from _pytest import nodes
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/nodes.py", line 11, in <module>
    from _pytest.mark.structures import NodeKeywords, MarkInfo
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/mark/__init__.py", line 4, in <module>
    from .structures import (
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/mark/structures.py", line 306, in <module>
    class MarkInfo(object):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/mark/structures.py", line 309, in MarkInfo
    _marks = attr.ib(converter=list)
TypeError: attrib() got an unexpected keyword argument 'converter'
```

Very similar to https://github.com/Julian/jsonschema/issues/449, https://github.com/pytest-dev/pytest/issues/3280, https://github.com/pytest-dev/pytest/pull/3228.

**Comment by rhcu** [comment]
One of dependencies installed with `pip` uses attrs>=17.3.0 (can be found here: https://travis-ci.org/mozilla/coverage-crawler/builds/420972230#L471), while the solution that they suppose is to use attrs>=17.4.0. Probably, this can be handwritten in requirements.txt?

**Comment by marco-c** [comment]
Maybe yes. Can you try putting attrs==17.4.0 in test-requirements.txt, update pytest and submit a PR with these changes? Then we'll see if Travis is happy.
