### ISSUE TITLE
TaskclusterFailure: rootUrl option is required

### ISSUE THREAD

**Issue by MadinaB** [mozilla/coverage-crawler#169]
Successfully followed steps `pip install -r requirements.txt` and `pip install -r test-requirements.txt` till this step `download_artifacts.py` where I got following error:

Traceback (most recent call last):
  File "download_artifacts.py", line 10, in <module>
    latest_cov_build.download_artifacts(args.revision)
  File "/Users/madinabektayeva/Documents/Programming/Outreachy/CodeCoverage/coverage-crawler/coverage_crawler/latest_cov_build.py", line 34, in download_artifacts
    index = taskcluster.Index()
  File "/usr/local/lib/python3.7/site-packages/taskcluster/client.py", line 64, in __init__
    raise exceptions.TaskclusterFailure('rootUrl option is required')
taskcluster.exceptions.TaskclusterFailure: rootUrl option is required

Looks like being after an update to Taskcluster 5.0. but I am not sure how to deal with it yet.

**Comment by MadinaB** [comment]
Created new virtual machine to run this project (Linux  x86_64) and again getting this error:
File "/usr/local/lib/python3.5/dist-packages/taskcluster/client.py", line 64, in __init__
    raise exceptions.TaskclusterFailure('rootUrl option is required')
taskcluster.exceptions.TaskclusterFailure: rootUrl option is required

Will try to resolve same way by replacing value of  'rootUrl' manually in /usr/local/lib/python3.5/dist-packages/taskcluster/client.py to 'https://taskcluster.net', but still sure that this error came from taskcluster itself.

**Comment by marco-c** [comment]
One easy way to fix this is to pin the taskcluster dependency to 4.0.1 in requirements.txt.
